### ISSUE TITLE
peer-to-peer review

### ISSUE THREAD

**Issue by denscholar** [sergiogval/sergiogval.github.i#11]
Hi @sergiogval,

Good job so far!
✔️ Linters are passing
✔️ Good UI

This is one of the hardest templates and you did it very well 👌. However,  there are some issues that you still need to work on

## Required Changes ♻️ 
- In the form section, in the mobile version, We think it should be better to adjust the size. This will further make your app mobile responsive.
- We think It would be better to resize the text area vertically instead of vertically and horizontally, you can also add this property `resize: vertical.
- We think it would be okay to add margin to the project section where you implemented the transition effect. 
- Some of the images are blurred. This could probably be the cause of the height and width set on the image. You might consider taking that off and using the background-size properties. 
- We think you should add the 'line height' property in the about text.
- On the mobile view, you did great but we also think you should consider using a media query to hide your navbar such that it will only show the hamburger icon.

<img src="https://media3.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>

**Comment by sergiogval** [comment]
#Thanks for you comments
***This problems have been solved***

You may find the new code on [this repo](https://github.com/sergiogval/sergiogval.github.io)

If you think this need further attention, please let me know over the other repo.

Meanwhile i'll be closing this issue.
