### ISSUE TITLE
Peer to peer code reviews

### ISSUE THREAD

**Issue by fherrerao** [sergiogval/sergiogval.github.i#7]
- Understand the code review process as a team effort.
- Understand the Microverse program code review flow.
- Write clear and professional code review comments.

**Comment by fherrerao** [comment]
- The coding looks well, he is taking care of the best practice of coding.
- Kindly, he has to take care of some linters errors.

**Comment by jpol01** [comment]
# This review goal is to  create a commit in the presenter's code (Sergio Valadez):

### Recomended changes :recycle: 
 
   -Fix the linter errors.

 #### You have done a great job keep working like that :checkered_flag:

**Comment by sergiogval** [comment]
thanks, always coding hard.
